services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: url_shortener
      JWT_SECRET: supersecret
      JWT_EXPIRES_IN: 3600s
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  pgdata:
