version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_db 
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: url-shortener-api
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    command: sh -c "npm run migration:run && npm run start:prod"
    volumes:
      - .:/app
    restart: always

volumes:
  pgdata: